<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends EntityRepository
{
  public function getBookingData($params){
    $qb = $this->getEntityManager()->createQueryBuilder();
    $qb->select('b')
      ->from('AppBundle:Booking','b')
      ->innerJoin('b.id','bgp')
      ->where('b.transaction = :transaction')
      ->setParameter('transaction',$params['id_transaction']);

    $qb->getQuery()->setQueryCacheLifetime(3600);
    $qb->getQuery()->setResultCacheLifetime(3600);
    $qb->getQuery()->useQueryCache(true);
    return $qb->getQuery()->getSingleResult(2);
  }
}
