<?php

namespace AppBundle\Repository;

/**
 * CollateralActivitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollateralActivitiesRepository extends \Doctrine\ORM\EntityRepository
{
}
