<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{
  public function findAllToArray(){
    $qb = $this->getEntityManager()->createQueryBuilder();
    $qb->select('c.id, c.country_name as name, c.country_code as code')
      ->from('AppBundle:Country','c');
    $qb->getQuery()->setQueryCacheLifetime(3600);
    $qb->getQuery()->setResultCacheLifetime(3600);
    $qb->getQuery()->useQueryCache(true);
    return $qb->getQuery()->getResult();
  }
}
