<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
    public function getMenus($parametersCollection)
    {
        $qb = $this->createQueryBuilder('m');
        $qb->select('m.id, m.name, m.slug, m.description')
            ->orderBy('m.created_date','DESC');

        $whereAdded = false;
        if(isset($parametersCollection['searchBySlug']) && $parametersCollection['searchBySlug'] == true){
            if(!$whereAdded)
            {
                $whereAdded = true;
                $qb->where("m.slug = '".$parametersCollection['slug']."' ");
            }
            else{
                $qb->andWhere("m.slug = '".$parametersCollection['slug']."' ");
            }
        }
        return $qb->getQuery()->getArrayResult();
    }

    public function deleteByIdsCollection($idsCollection)
    {
        $em = $this->getEntityManager();
        $queryText = "DELETE FROM AppBundle:Menu m
                      WHERE m.id IN (".$idsCollection.")";
        $query = $em->createQuery($queryText);
        $query->execute();
    }
}
