<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NomFunctionalityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomFunctionalityRepository extends EntityRepository
{
    public function getFunctionalities($parametersCollection)
    {
        $qb = $this->createQueryBuilder('f');
        $qb->select('f.url_index_action, f.keyword_selected_class, f.icon_class,
                     f.is_used_frequently,
                     n.id, n.name_es, n.url_slug_es, n.tree_slug')
            ->innerJoin('f.id', 'n');

        $whereAdded = 0;
        /*filtering by TREE_SLUG*/
        if($parametersCollection['filterByTreeSlug'] == true && $parametersCollection['treeSlug'] != null){
            if(!$whereAdded){
                $qb->where("n.tree_slug LIKE '%".$parametersCollection['treeSlug']."%' ");
            }
            else{
                $qb->andWhere("n.tree_slug LIKE '%".$parametersCollection['treeSlug']."%' ");
            }
        }


        return $qb->getQuery()->getArrayResult();
    }
}
