<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NomTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomTypeRepository extends EntityRepository
{

}
