<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RepertoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepertoryRepository extends EntityRepository
{

}
