<?php

namespace AppBundle\Repository;

/**
 * ShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShowRepository extends \Doctrine\ORM\EntityRepository
{
}
