<?php

namespace AppBundle\Repository;

/**
 * ShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShowRepository extends \Doctrine\ORM\EntityRepository
{
  public function getShowsFullData($parametersCollection){
    $date = new \DateTime();
    $qb = $this->getEntityManager()->createQueryBuilder();

    $selectChain = "sgp.id, sgp.url_slug_{$parametersCollection['currentLanguage']} as url_slug, sgp.title_{$parametersCollection['currentLanguage']} as title, 
    r.id as idroom, s.showDate as date_show";

    $qb->select($selectChain)
       ->from('AppBundle:Show','s')
       ->innerJoin('s.id','sgp')
       ->innerJoin('s.room','r')
       ->orderBy('s.showDate');

    if($parametersCollection['home'] != 'false'){
      $qb->andWhere('s.showDate >= :show_date')
        ->setParameter('show_date',$date);
    }

    $qb->getQuery()->setQueryCacheLifetime(3600);
    $qb->getQuery()->setResultCacheLifetime(3600);
    $qb->getQuery()->useQueryCache(true);
    return $qb->getQuery()->getResult();
  }
}
