<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaxonomyTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxonomyTypeRepository extends EntityRepository
{
    public function getTaxonomyTypes($parametersCollection)
    {
        $qb = $this->createQueryBuilder('tt');
        $qb->select('tt.id, tt.name_es, tt.description_es, tt.url_slug_es, tt.tree_slug');

        $whereAdded = 0;
        if(isset($parametersCollection['filterByTreeSlug']) && $parametersCollection['filterByTreeSlug'] == true &&
            $parametersCollection['treeSlug'] != null ){
            if(!$whereAdded){
                $qb->where("tt.tree_slug LIKE '%".$parametersCollection['treeSlug']."%' ");
            }
            else{
                $qb->andWhere("tt.tree_slug LIKE '%".$parametersCollection['treeSlug']."%' ");
            }
        }

        $qb->orderBy('tt.id','DESC');
        return $qb->getQuery()->getArrayResult();
    }
}
