<?php

namespace AppBundle\Repository;

/**
 * ZoneRowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoneRowRepository extends \Doctrine\ORM\EntityRepository
{
}
