imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: "%app.locale%"

framework:
    #esi:             ~
    translator:      { fallbacks: ["%app.locale%"] }
    secret:          "%app.secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%app.default_locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true


# Twig Configuration
twig:
    globals:
        pathToWeb: "%kernel.root_dir%/../web"
        assets_css_base_scripts_version: "?version=%app.assets_css_base_scripts_version%"
        assets_css_plugins_scripts_version: "?version=%app.assets_css_plugins_scripts_version%"
        assets_css_customs_scripts_version: "?version=%app.assets_css_customs_scripts_version%"
        assets_js_base_scripts_version: "?version=%app.assets_js_base_scripts_version%"
        assets_js_plugins_scripts_version: "?version=%app.assets_js_plugins_scripts_version%"
        assets_js_base_angular_scripts_version: "?version=%app.assets_js_base_angular_scripts_version%"
        assets_js_app_angular_scripts_version: "?version=%app.assets_js_app_angular_scripts_version%"
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        "%kernel.root_dir%/../src/AppBundle/Resources/views/Backend": app_backend_template_directory
        "%kernel.root_dir%/../src/AppBundle/Resources/views/Frontend": app_frontend_template_directory
        "%kernel.root_dir%/../src/AppBundle/Resources/views/Shared": app_shared_template_directory

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%app.database_host%"
        port:     "%app.database_port%"
        dbname:   "%app.database_name%"
        user:     "%app.database_user%"
        password: "%app.database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%app.mailer_transport%"
    host:      "%app.mailer_host%"
    username:  "%app.mailer_user%"
    password:  "%app.mailer_password%"
    spool:     { type: memory }

# LiipImagine Images Configuration
liip_imagine:
    resolvers:
         default:
              web_path:
                   web_root: %kernel.root_dir%/../web
                   cache_prefix: uploads/images/liip_imagine_filtered
    filter_sets:
         cache: ~
         # the name of the "filter set"
         logued_user_thumbnail:
               # list of transformations to apply (the "filters")
               filters:
                    # create a thumbnail: set size to 120x90 and use the "outbound" mode
                    # to crop the image when the size ratio of the input differs
                    thumbnail: { size: [35, 35], mode: outbound }
                    # create a 2px black border: center the thumbnail on a black background
                    # 4px larger to create a 2px border around the final image
                    #background: { size: [124, 94], position: center, color: '#000000' }
         media_image_standard_thumbnail:
               filters:
                   thumbnail: { size: [120, 120], mode: outbound }

         featured_image_mini_thumbnail:
               quality: 75
               filters:
                    thumbnail: { size: [100, 125], mode: outbound }

         grid_featured_image_thumbnail:
               quality: 90
               filters:
                   thumbnail: { size: [320, 320]}

         list_featured_image_mini_thumbnail:
              quality: 90
              filters:
                  thumbnail: { size: [70, 70], mode: outbound }

         default_theme_banner:
             quality: 100
             filters:
                 thumbnail: { size: [1920, 900], mode: outbound }

         home_news_summary_featured_image_thumbnail:
             quality: 80
             filters:
                thumbnail: { size: [580, 380], mode: outbound }

         single_post_featured_image:
              quality: 100
              filters:
                  thumbnail: { size: [1280, 420], mode: outbound }