fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

app_bundle:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /logout

api:
    type: rest
    resource: "@AppBundle/Controller/ApiController.php"
    prefix:   /api
    methods:  [GET, POST, OPTIONS]
