# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        user_db:
            entity: { class: AppBundle\Entity\User, property: user_name }


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous:  true
            form_login:
                login_path: /login
                check_path: /login
                default_target_path: dashboard_index
                always_use_default_target_path: true
                csrf_provider: security.csrf.token_manager
            logout:
                path:   /logout
                target: /login

    access_control:
        - { path: ^/,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/*,  roles: IS_AUTHENTICATED_FULLY }
