# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
     login_listener:
         class: AppBundle\Listener\LoginListener
         arguments: [@doctrine.orm.entity_manager,@router]
         tags:
             - { name: kernel.event_listener, event: security.interactive_login }

     appbundle_accesvoter:
         class: AppBundle\Security\AccesVoter
         arguments: [@session,@doctrine.orm.entity_manager]
         tags:
             - { name: security.voter }

     appbundle_site_settings:
         class: AppBundle\Services\SettingServices
         arguments: [@session,@doctrine.orm.entity_manager]

     appbundle_file_finder:
              class: AppBundle\Services\FileFinderServices
              arguments: [@session,@doctrine.orm.entity_manager]

     appbundle_slugger:
          class: AppBundle\Services\SlugServices
          arguments: [@session,@doctrine.orm.entity_manager]

     appbundle_nomenclatures:
          class: AppBundle\Services\NomenclatureServices
          arguments: [@session,@doctrine.orm.entity_manager]

     appbundle_taxonomies:
          class: AppBundle\Services\TaxonomyServices
          arguments: [@session,@doctrine.orm.entity_manager]

     appbundle_events:
         class: AppBundle\Services\EventServices
         arguments: [@session,@doctrine.orm.entity_manager]

     appbundle_generic_posts:
          class: AppBundle\Services\GenericPostServices
          arguments: [@session,@doctrine.orm.entity_manager]
     appbundle_generate_seats:
          class: AppBundle\Services\SeatsGenerationServices
          arguments: [@session,@doctrine.orm.entity_manager]



#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
